/**
 * Copyright (c) HashiCorp, Inc.
 * SPDX-License-Identifier: MPL-2.0
 */

// generated by cdktf get
Object.defineProperty(exports, 'certRequest', { get: function () { return require('./cert-request'); } });
Object.defineProperty(exports, 'locallySignedCert', { get: function () { return require('./locally-signed-cert'); } });
Object.defineProperty(exports, 'privateKey', { get: function () { return require('./private-key'); } });
Object.defineProperty(exports, 'selfSignedCert', { get: function () { return require('./self-signed-cert'); } });
Object.defineProperty(exports, 'dataTlsCertificate', { get: function () { return require('./data-tls-certificate'); } });
Object.defineProperty(exports, 'dataTlsPublicKey', { get: function () { return require('./data-tls-public-key'); } });
Object.defineProperty(exports, 'provider', { get: function () { return require('./provider'); } });

